name: Next Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Create next release'
        required: true
        type: boolean
        default: true

jobs:
  release:
    name: Create Next Release
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.changesets.outputs.published }}
      version: ${{ steps.changesets.outputs.version }}
      sha: ${{ steps.sha.outputs.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Get short SHA
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create Next Release
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun run version:next
          publish: bun run release:next
          commit: "chore: version packages (next)"
          title: "chore: version packages (next)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-next:
    needs: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: api
            dockerfile: docker/api.Dockerfile
            image: questpie/bulkitdev-api
          - name: worker
            dockerfile: docker/worker.Dockerfile
            image: questpie/bulkitdev-worker
          - name: app
            dockerfile: docker/app.Dockerfile
            image: questpie/bulkitdev-app
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ matrix.image }}:next
            ${{ matrix.image }}:next-${{ needs.release.outputs.sha }}
            ${{ matrix.image }}:next-${{ needs.release.outputs.version }}

      - name: Update GitHub Release
        if: needs.release.outputs.published == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.release.outputs.version }}-next
          prerelease: true
          body: |
            This is a preview release.

            Docker Images:
            - API: `questpie/bulkitdev-api:next-${{ needs.release.outputs.version }}`
            - Worker: `questpie/bulkitdev-worker:next-${{ needs.release.outputs.version }}`
            - App: `questpie/bulkitdev-app:next-${{ needs.release.outputs.version }}`

            Commit: ${{ needs.release.outputs.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}