name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.changesets.outputs.published }}
      version: ${{ steps.changesets.outputs.version }}
      sha: ${{ steps.sha.outputs.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Get short SHA
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create Release
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun run version
          publish: bun run release
          commit: "chore: version packages"
          title: "chore: version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-release:
    needs: release
    if: needs.release.outputs.published == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: api
            dockerfile: docker/api.Dockerfile
            image: questpie/bulkitdev-api
          - name: worker
            dockerfile: docker/worker.Dockerfile
            image: questpie/bulkitdev-worker
          - name: app
            dockerfile: docker/app.Dockerfile
            image: questpie/bulkitdev-app
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: |
            ${{ matrix.image }}:latest
            ${{ matrix.image }}:${{ needs.release.outputs.sha }}
            ${{ matrix.image }}:${{ needs.release.outputs.version }}

      - name: Update GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.release.outputs.version }}
          body: |
            Docker Images:
            - API: `questpie/bulkitdev-api:${{ needs.release.outputs.version }}`
            - Worker: `questpie/bulkitdev-worker:${{ needs.release.outputs.version }}`
            - App: `questpie/bulkitdev-app:${{ needs.release.outputs.version }}`

            Commit: ${{ needs.release.outputs.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}