name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        if: steps.changesets.outputs.published == 'true'
        run: |
          TAG=$(git describe --tags --abbrev=0)
          gh release create $TAG -F CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push bulkit-api
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/api.Dockerfile
          push: true
          tags: questpie/bulkit-api:latest,questpie/bulkit-api:${{ steps.changesets.outputs.version }}

      - name: Build and push bulkit-worker
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/worker.Dockerfile
          push: true
          tags: questpie/bulkit-worker:latest,questpie/bulkit-worker:${{ steps.changesets.outputs.version }}

      - name: Build and push bulkit-app
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/app.Dockerfile
          push: true
          tags: questpie/bulkit-app:latest,questpie/bulkit-app:${{ steps.changesets.outputs.version }}
s